---
local:
  prompt: "[user@laptop ~]$"
  bash_shebang: "#!/bin/bash"

snippets: EPCC_ARCHER2_slurm
baseurl: "https://epcced.github.io/2023-06-28-uoe-hpcintro"

remote:
  name: "ARCHER2"
  host_id: "EPCC_ARCHER2"
  login: "login.archer2.ac.uk"
  host: "ln03"
  node: "nid001053"
  location: "EPCC, The University of Edinburgh"
  homedir: "/home/ta114/ta114/"
  user: "userid"
  prompt: "userid@ln03:~>"
  prompt_work: "userid@uan01:/work/ta114/ta114/userid>"
  module_python3: "cray-python"
  bash_shebang: "#!/bin/bash"

sched:
  name: "Slurm"
  partition: "standard"
  reservation: "shortqos"
  qos: "short"
  budget: "short"
  submit:
    name: "sbatch"
    options: "--partition=standard --qos=short"
  queue:
    debug: ""
    testing: ""
  status: "squeue"
  flag:
    user: "-u userid"
    interactive: ""
    histdetail: "-l -j"
    name: "--job-name"
    time: "--time"
    queue: "--partition"
    nodes: "--nodes"
    tasks: ""
  del: "scancel"
  interactive: "srun"
  info: "sinfo"
  comment: "#SBATCH"
  hist: "sacct"
  project: ta114
